# docker compose up -d
# docker exec -it [mysql container name] bash
# docker logs [mysql container name]

services:  
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - "${MYSQL_PORT}"
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "docker.for.mac.localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: cmd/web/Dockerfile.dev
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DSN=${APP_DSN}
      - APP_PORT=${APP_PORT}
    command: ./cmd/web
    # command: ./cmd/web -debug=true
    develop:
      watch:
        - action: sync
          x-initialSync: true
          path: ./ui/static
          target: /snippetbox/ui/static
        - action: rebuild
          path: ./ui/html
        - action: rebuild
          path: ./cmd/web

